[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.23"
via_ir = true
optimizer = true
optimizer_runs = 200

# for ZK proofs
fs_permissions = [{ access = "write", path = "./"}]

# Remappings
remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
	"@semaphore/contracts/=lib/semaphore/packages/contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options